pipelines:
  - name: testConditional_resource
    configuration:
      # Set the inputResources conditionally based on the branch
      {{ if eq "main" "{{gitBranch}}" }}
      inputResources:
        - name: resource_pipelines
          trigger: true
      {{ else }}
      inputResources:
        - name: resource_pipelines
          trigger: false
      {{ end }}
    steps:
      - name: execute_script
        type: Bash
        execution:
          onExecute:
            - echo "hello world"
