resources:
  - name: resource_pipelines
    type: GitRepo
    configuration:
      gitProvider: agrasth #rename to your integration name
      path: agrasth/samplePipeline #rename to your repo name
pipelines:
  - name: test
    configuration:
      inputResources:
        - name: resource_pipelines
    steps:
      - name: execute_script
        type: Bash
        execution:
          onExecute:
            - pushd $res_resource_pipelines_resourcePath
            - pwd
            - ./script.sh # copy contents for script.sh file
            - popd
            
