pipelines:
  - name: test
    configuration:
      inputResources:
        - name: resource_pipelines
    steps:
      - name: execute_script
        type: Bash
        execution:
          onExecute:
            - pushd $res_resource_pipelines_resourcePath
            - pwd
            - ls
            - pushd test
            - ./script.sh
            
            
