pipelines:
  - name: pipelines_build
    configuration:
      # Set the inputResources conditionally based on the branch
      {{ if eq "master" "{{gitBranch}}" }}
      inputResources:
        - name: resource_pipelines
          trigger: true
      {{ else }}
      inputResources:
        - name: resource_pipelines
          trigger: false
      {{ end }}
    steps:
      - name: execute_script
        type: Bash
        configuration:
          inputResources:
            - name: resource_pipelines
          execution:
            onExecute:
              - echo "hello world"
